### ISSUE TITLE
Question about the logout

### ISSUE THREAD

**Issue by JRMaitre** [joshuaslate/mern-starter#19]
Hi, I'm very new to React and it's highly possible I'm doing something wrong but I can't figure out if it's a bug or just me not understanding so I'll ask anyway!

There's an action in actions/auth.js that is used to logoutUser. It works properly if you use the /logout route. However, if I don't require auth on the route to GET the API, and that it then sends back a 401 (we agree that it shouldn't but let's say my token expired in the back-end), then we send the error to the errorHandler. When we do that, it then checks for a 401, and if that's a 401, it calls the logoutUser function.

For me, this doesn't work, because it doesn't do anything except call that function, but that function returns a function and we don't do anything with it. 

Now I found a way to make it work by passing the "dispatch" object from the errorHandler to the logoutUser function, and use that directly in that function. But I'm pretty sure that's now how it's supposed to work so I was wondering if you could explain to me what I'm missing?

Other than that, I just want to say thank you for your blogs and your starter project, it has helped me an incredible amount and finally me got me started in learning React, so THANK YOU! :)

**Comment by joshuaslate** [comment]
Hi,

This is a mistake I've made and haven't had time to fix yet. I'm working on a few projects I need to get done first, but I'll come back and make some big changes to this repo within the new few months, I'd imagine. A quick explanation of why it isn't working is because dispatch isn't being injected in the call to logoutUser(). Our component, thanks to connect(), injects dispatch when calling our action creators. You could try changing the call to dispatch(logoutUser()), otherwise, simply dispatch the UNATUH_USER for the time being from the errorHandler, and I'll try to come up with something more elegant down the road!

Please let me know if that works for you. I'm shooting from the hip and am not able to test this right now.

Thanks!

**Comment by JRMaitre** [comment]
Yes that works for me, thanks for your help :)
